# Generated by Django 4.1.4 on 2022-12-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atp.bills'),
        ),
    ]
