# Generated by Django 4.1.4 on 2022-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0002_alter_bills_value_alter_box_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='storage',
        ),
    ]
