# Generated by Django 4.1.4 on 2022-12-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0003_request_remove_box_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='transaction_text',
            field=models.CharField(default='Soy un cajero malo, he sido malo y no puedo darte esa cantidad', max_length=100),
        ),
    ]
