# Generated by Django 4.1.4 on 2022-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0004_request_transaction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request',
            field=models.IntegerField(default=0),
        ),
    ]
