# Generated by Django 4.1.4 on 2023-01-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0005_request_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='total',
        ),
    ]
