# Generated by Django 4.1.4 on 2023-01-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0006_transaction_remove_request_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
