# Generated by Django 4.1.4 on 2023-01-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atp', '0007_box_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
    ]
